services:
  web:
    build: .
    container_name: cinema-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - redis
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7-alpine
    container_name: cinema-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data

  celery-worker:
    build: .
    container_name: cinema-celery-worker
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A src.tasks:celery_app worker --loglevel=info

  celery-beat:
    build: .
    container_name: cinema-celery-beat
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A src.tasks:celery_app beat --loglevel=info
